### ISSUE TITLE
channel could be updated with invalid/none exist clients

### ISSUE THREAD

**Issue by jiangytcn** [mainflux/manager#2]
master branch with latest code

→ git rev-parse HEAD
34ef2d224c9cca0b31eb08c4ca28aed9226b04a9

 → curl -s -i -S -X PUT -H "Content-Type: application/senml+json" -H "Authorization: $USER_TOKEN" localhost:8180/channels/6b3bc068-92ac-11e7-9297-0242ac120006 -d '{"name":"mychan", "connected": ["none-exist-client"]}'

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 06 Sep 2017 02:51:12 GMT
Content-Length: 0

cassandra@cqlsh:system_distributed> SELECT  * FROM clients_by_channel ;

 id                                   | user                 | connected
--------------------------------------+----------------------+-----------------------
 6b3bc068-92ac-11e7-9297-0242ac120006 | jiangyt.cn@gmail.com | {'none-exist-client'}

**Comment by mijicd** [comment]
@jiangytcn First of all, thanks for raising the issue. I'm aware of this problem being present in the current version. It is an intentional decision due to the fact that the client identifiers (which should be stored in the `connected` list) are auto-generated values. Hence, adding random values to the channel won't affect the permissions checking. However, it is something we might need to modify in the future.

**Comment by drasko** [comment]
@mijicd my concern is that issuing API call for connecting clients is prone to errors (from caller side for example). This will pollute database and leave confusing artifacts in the table.

This is not priority now, but IMHO these calls should be validated by backend and refused - users should be informed with error messages and guided towards correct usage of the system.

I don't know how this affect performance of the system (you have to read db each time to check if device exists), but I expect these provisioning calls to come  less frequently than IoT messaging calls.

**Comment by jiangytcn** [comment]
Its better there's one place to  track the backlogs, [Trello](https://trello.com/) something like that. 
And just as @drasko said, the users will confuse about such API call, but its not the high priority
